<a href="https://colab.research.google.com/github/wldnjs0122/2026-BDA/blob/main/0318_%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 내장함수 arange()와 linspace()

In [1]:
import numpy as np

print(np.arange(3)) # 0~2까지
print(np.arange(3, 7))
print(np.arange(3, 7, 2)) # 스템, 2씩 증가

[0 1 2]
[3 4 5 6]
[3 5]


In [6]:
print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [5]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [10]:
# np.reshape(a, (3, 5)) 원소가 15개인데 원래 배열 원소는 12개이기 때문에 오류

In [11]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [12]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [13]:
print( (3-2) / (50-1))

0.02040816326530612


In [14]:
np.linspace(2, 3, 3, retstep = True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [17]:
a = np.linspace(2, 3, 3, retstep = True)
float(a[1])

0.5

In [19]:
np.linspace(2, 3, 3, retstep = True, endpoint = False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [20]:
(3-1) / 3

0.6666666666666666

### 내장함수 zeros ones empty

In [21]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [22]:
a.dtype

dtype('float64')

In [23]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [24]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [25]:
np.zeros((2,3)) # 괄호 없으면 오류

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [30]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [31]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
b = np.eye(3, 4, -1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [32]:
np.full([2,3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [34]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [35]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [37]:
np.full((4, 3), np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### sum

In [38]:
a = np.array(([3, 5, 8], [1, 2, 3]))

In [40]:
# 일차원으로 펼쳐서 계산
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [41]:
a.cumsum(axis=0) # 시험예상, 행을 따라 세로로 합산

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [42]:
a.cumsum(axis=1) # 시험예상, 행을 따라 가로로 합산

array([[ 3,  8, 16],
       [ 1,  3,  6]])

### 배열 슬라이싱

In [43]:
a = np.power(np.arange(10), 2)

In [45]:
print(a[3])
print(a[-2])

9
64


In [46]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [47]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [48]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
a[3] # 행이 우선

array([18, 19, 20, 21, 22, 23])

In [50]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [51]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [52]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [54]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [55]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [56]:
# a[ , 1] 비우면 오류

In [57]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [59]:
a[:, 1:6] # 모든 행에 대해서 1에서부터 6 전까지

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [62]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [63]:
a[2, 4]

np.int64(16)

In [64]:
a[2][4]

np.int64(16)

In [65]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [61]:
a[::-1, ::-1] # 시험문제 나올 수도, 행과 열 모두 역순

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [66]:
a[:-1, :-1] # 마지막 행과 열을 제외한 배열 반환

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [69]:
# 3차원 배열의 다양한 참조 시험문제 가능
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [70]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [71]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [72]:
a[:, 1, 1]

array([ 5, 17])

In [73]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [74]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [75]:
a[1, ..., 1] # a[1, ;, 1] 과 같음

array([13, 17, 21])

In [76]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

### 브로드캐스팅 - 서로 다른 모양의 배열 연산을 수행

### 고급 색인

In [79]:
import numpy as np
x = np.arange(10)
10

10

In [80]:
x[1]

np.int64(1)

In [81]:
x[:5] # 처음부터 인덱스 4까지

array([0, 1, 2, 3, 4])

In [85]:
x[ [2] ] # 대괄호 - 배열 생성

array([2])

In [84]:
x[ [2, 3] ]

array([2, 3])

In [86]:
x[ [2, 3, 2, 5, 8]]

array([2, 3, 2, 5, 8])

In [88]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [89]:
x[0, 1] # 0행 1열

np.int64(1)

In [90]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [91]:
x[..., 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [93]:
x[ [0], [1] ]

array([1])

In [94]:
x[ [0,1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [95]:
x[ [1, 3, 5] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [98]:
x[ [1, 3, 5], : ] # 똑같다

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [99]:
x[ [1, 3], [2, 2] ]

array([10, 26])

In [101]:
x[ [1, 3], [2, 3] ]

array([10, 27])

In [102]:
x[ [0, 2, 4], [1] ]

array([ 1, 17, 33])

In [104]:
x[ [0, 2, 4], 1] # 똑같다!

array([ 1, 17, 33])

In [105]:
x[ [0, 2, 4], :2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [106]:
x[ [0, 2, 4], [1, 1, 1]]

array([ 1, 17, 33])

In [108]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [109]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [110]:
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [111]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [112]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [113]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [114]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [115]:
a[np.arange(2, 4)][:, [1,0]]

array([[17, 16],
       [25, 24]])

In [117]:
a[np.arange(2, 4)][:, [1, 1, 1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [118]:
a[np.arange(2, 4)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [119]:
a[[2, 3]][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [121]:
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [122]:
a[ [2, 3, 4] ]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [123]:
a[[2, 3, 4]][:, [-1, -2, -3, -4, -5, -6, -7]]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])